### ISSUE TITLE
How can I check if tagbar is open or closed?

### ISSUE THREAD

**Issue by tal-zvon** [preservim/tagbar#717] opened 2020-12-06 15:37 UTC
Is it possible to check in my .vimrc file if Tagbar is open or closed in an if-statement?

**Comment by terminator14** [comment] 2020-12-06 22:42
Best I found so far is this:

```
function TagbarIsOpen()
    let windows = []
    windo call add(windows, bufname('%')) 

    for item in windows
        if stridx(item, "Tagbar") != -1       
            return 1
        endif
    endfor

    return 0
endfunction
```

Is there an easier way to do this?

**Comment by alerque** [comment] 2020-12-07 08:32
No off the top of my head I don't think there is anything builtin. A utility function like you describe is probably in order.

THat being said the extra array iteration seems a little bit more complex that I expect is necessary. Have you tried using `bufwinnr()` or `bufexists()` to search?

When you do get a simple boolean check working well it would be nice to see a PR that contributes it upstream so others can benefit.

**Comment by terminator14** [comment] 2020-12-09 16:20
I am less than useless when it comes to writing code in vimscript - the above function is just something I threw together. I have not heard of `bufwinnr()`, or `bufexists()`, and up until a few days ago when I wrote that function, I had not heard of `stridx` either.

As far as I can tell, tagbar can already internally tell if it's open or closed in the `ToggleWindow` function. All someone would have to do is create a global variable that would be set that's True when Tagbar is open, and False when it's closed (or, you know, 0 and 1, since vimscript doesn't have bool).

Then, code in `.vimrc` can use that variable.

As an alternative, in addition to this global variable, Tagbar could also introduce a function that would read this variable, and return the result. That way, instead of checking a global variable, `.vimrc` would make a function call. Not sure which is better.

Does that sound right?

**Comment by raven42** [comment] 2020-12-09 16:52
There is actually not any internal variable that tracks if the tagbar window is open. The `TagbarToggle` command performs the search similar to what @alerque mentioned. The problem is the user can manually close windows or move them around. So tracking something internally would be problematic. Instead we have to search for the window every time we need to reference it.

Here is a similar bit of code to what tagbar does:
```vim
let tagbarwinnr = bufwinnr('__Tagbar__')
if tagbarwinnr != -1
    " Window open... close it if needed
else
    " Window not open... open if needed
endif
```

As for your specific use case, have you tried using the following?
```vim
set mouse=a
set clipboard=unnamed,autoselect,exclude:cons\|linux
```

This will allow vim to recognize the mouse and allow highlighting (visual selection mode) of the lines in the active vim window, not the entire terminal window. Then it also uses the system clipboard when something is visually selected. Technically you wouldn't even need the `set mouse=a` option, you could just use visual mode to select the text you want with the keyboard.

Note: this does change the behavior a little bit if you are a using `visual` mode a lot to select text and paste over it. Might take a little getting used to, but I'd recommend learning to use the VIM registers to copy/paste to/from instead of the default register. See `:help registers` for more info.

As another alternative, I have a plugin that integrates tagbar/nerdtree together if you're interested. The toggle on that can be hotkeyed, and it also toggles the `set number`. Wouldn't be hard to add any additional options to toggle in there as well. [DevPanel](https://github.com/raven42/devpanel-vim)

**Comment by terminator14** [comment] 2020-12-09 17:44
Thanks - I can update my function to use that code instead - seems cleaner and shorter.

From what I understand, using the system clipboard like you describe requires vim to be compiled with `+clipboard`. Both the vim that comes with my Fedora, and the vim that comes with my CentOS 7 have `-clipboard`. I've read somewhere that you can still set vim up to use external tools to add the ability to copy things to the system clipboard, but those external tools might be different, depending on if you're using vim on MacOS, or Linux.

Some of those external clipboard tools even rely on X11, or Wayland, and on a headless server, neither would be present. There's no X11 or Wayland on MacOS either (at least by default).

Either I'm way off, or it sounds like there's no easy, portable way to have vim use the system clipboard.
I'll learn about registers, but it sounds like they're only internal to vim, and can't be used to copy things to other apps, like if I want to copy a few lines, and paste them into an email in my browser.

Setting `set mouse=` (disabling mouse support), and hiding anything that might interfere with the selection of lines (NERDTree, Tagbar, line numbers, etc), sounds like the most portable way, that works on every system everywhere. It obviously has its downsides - besides requiring for all the stuff above to be disabled, you also can't select more lines than your terminal can display. 95% of the time though, the lines I want copied fit in my terminal.

**Closed** 2021-01-06 12:23 UTC
Labels: pr-welcome, question
