### ISSUE TITLE
Tagbar doesn't recognize TypeScript support

### ISSUE THREAD

**Issue by joshfrench** [preservim/tagbar#668] opened 2020-09-30 23:31 UTC
I'm using u-ctags, which does support typescript:
```
$ /usr/local/bin/ctags --list-kinds-full=typescript
#LETTER NAME       ENABLED REFONLY NROLES MASTER DESCRIPTION
C       constant   yes     no      0      NONE   constants
G       generator  yes     no      0      NONE   generators
a       alias      yes     no      0      NONE   aliases
[etc.]
```
However, when I open a .ts file in nvim the TagBar window is empty. Using `TagbarDebug` it appears that Tagbar doesn't recognize u-ctag's typescript support:
```
1970-01-20 04:15:41.503553: Vim filetype: 'typescript', sanitized filetype: 'typescript'
1970-01-20 04:15:41.503687: Checking if file is valid [/Users/jfrench/src/test.ts]
1970-01-20 04:15:41.503887: Unsupported filetype: typescript
1970-01-20 04:15:41.504017: Not a valid file, stopping processing
```
I have `g:tagbar_ctags_bin` set to the same bin used above. Using the ctags command from `tagbar-issues` help, I am able to correctly generate tags from the same bin and test file.

**Comment by alerque** [comment] 2020-10-01 06:43
Have you seen #496? I think this is a duplicate of that. The short version seems to be that we don't have TS tag definitions baked in yet. There are some on the Wiki you can add to your RC file, but so far nobody has contributed them as a PR to the core. I'd be happy to accept such a contribution, all we need is somebody that works with TypeScript to add the mapping as defaults to Tagbar and do a little sanity checking to make sure the results are as expected.

**Closed by alerque** 2020-10-01 06:43 UTC
