### ISSUE TITLE
Use tag end field to not show as being part of previous tag

### ISSUE THREAD

**Issue by narcolepsy** [preservim/tagbar#508] opened 2018-10-30 13:09 UTC
When using tags in large files with many functions there are some times when the tagbar status line will show the tag above the cursor, even if outside that tags' scope:

OK:
![image](https://user-images.githubusercontent.com/210637/47719952-a17cd600-dc44-11e8-8747-8609d3f63604.png)

Also OK:
![image](https://user-images.githubusercontent.com/210637/47719971-b194b580-dc44-11e8-90b6-89b3a370acf2.png)

Not OK:
![image](https://user-images.githubusercontent.com/210637/47719983-ba858700-dc44-11e8-8b66-db0011bccadb.png)

I have looked at turning on all of the tag fields for cpp and this does indeed generate an end tag, but it is ignored by tagbar:
![image](https://user-images.githubusercontent.com/210637/47720068-eb65bc00-dc44-11e8-9a5b-106ce5db2e3d.png)

The tags file was built with ```ctags --fields=* test.cpp```

If you require more information please let me know

**Comment by tmandry** [comment] 2019-03-25 23:39
This is especially unfortunate in languages where you can have items nested inside of functions. In Rust, sometimes there is an `enum` at the top of a function for example, and when putting your cursor in the entire rest of the function, the statusline shows the enum name instead of the function name.

**Comment by bam80** [comment] 2019-03-26 15:21
Hm, didn't know there is end tag, interesting..
Meanwhile, you could look at [StlShowFunc](https://github.com/dr-chip-vim-scripts/StlShowFunc) plugin - it respects function ends and doesn't rely on tags.
I would be very grateful if you test  [staging](https://github.com/dr-chip-vim-scripts/StlShowFunc/tree/staging) branch - I improved it there and maintaining it now. Needs testing to merge.

**Comment by alerque** [comment] 2020-04-27 07:47
We would love to have end tag tracking support in tagbar (for supported languages of course). If anybody is willing to make it happen we would be sure to help facilitate PR review and merger.

For anybody working on this issue #399 is an earlier duplicate of this issue from before it was possible. [This comment](https://github.com/majutsushi/tagbar/issues/399#issuecomment-417404339) has some good notes on the Universal Ctags implementation and [this comment](https://github.com/majutsushi/tagbar/issues/399#issuecomment-619625284) has some good links with related implementations.

**Closed** 2020-11-02 21:15 UTC
Labels: feature, pr-welcome
