### ISSUE TITLE
Airline integration issue

### ISSUE THREAD

**Issue by vito-c** [preservim/tagbar#455] opened 2017-11-02 21:06 UTC
https://github.com/vim-airline/vim-airline/issues/1588
Please see this issue above. They asked me to open it here :)

**Comment by majutsushi** [comment] 2017-12-03 02:55
Hmm, that's not a lot of information to go on. Are you using Exuberant Ctags or Universal Ctags? Do you have jsctags installed? Do you have any custom type definitions? Do you have an example of a file where this happens? Could you please create a logfile as described under `:h tagbar-issues`? Thanks!

**Comment by FelixZhang** [comment] 2019-01-07 11:55
Same issue here:

- Using Exuberant Ctags 5.8 shipped on openSUSE Leap 15.0
- jsctags not installed
- Example file at https://github.com/GNOME/gjs/blob/master/modules/lang.js
- Logfile content as:

> VIM - Vi IMproved 8.0 (2016 Sep 12) 
Included patches: 1-1568
Compiled by 'http://www.opensuse.org/'
Huge version without GUI.  Features included (+) or not (-):
+acl               +cmdline_compl     -ebcdic            -hangul_input      +lua/dyn           +mouse_xterm       +python/dyn        +tag_binary        +vertsplit         -xpm
+arabic            +cmdline_hist      +emacs_tags        +iconv             +menu              +multi_byte        +python3/dyn       +tag_old_static    +virtualedit       -xsmp
+autocmd           +cmdline_info      +eval              +insert_expand     +mksession         +multi_lang        +quickfix          -tag_any_white     +visual            -xterm_clipboard
-autoservername    +comments          +ex_extra          +job               +modify_fname      -mzscheme          +reltime           -tcl               +visualextra       -xterm_save
-balloon_eval      +conceal           +extra_search      +jumplist          +mouse             +netbeans_intg     +rightleft         +termguicolors     +viminfo        
+balloon_eval_term +cryptv            +farsi             +keymap            -mouseshape        +num64             +ruby/dyn          +terminal          +vreplace   
-browse            +cscope            +file_in_path      +lambda            +mouse_dec         +packages          +scrollbind        +terminfo          +wildignore  
++builtin_terms    +cursorbind        +find_in_path      +langmap           -mouse_gpm         +path_extra        +signs             +termresponse      +wildmenu      
+byte_offset       +cursorshape       +float             +libcall           -mouse_jsbterm     +perl              +smartindent       +textobjects       +windows     
+channel           +dialog_con        +folding           +linebreak         +mouse_netterm     +persistent_undo   +startuptime       +timers            +writebackup
+cindent           +diff              -footer            +lispindent        +mouse_sgr         +postscript        +statusline        +title             -X11            
-clientserver      +digraphs          +fork()            +listcmds          -mouse_sysmouse    +printer           -sun_workshop      -toolbar           -xfontset
-clipboard         -dnd               +gettext           +localmap          +mouse_urxvt       +profile           +syntax            +user_commands     -xim         
   system vimrc file: "/etc/vimrc"
    ¦user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
    ¦ user exrc file: "$HOME/.exrc"
    ¦  defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -Wall -pipe -fno-strict-aliasing -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26.1/x86_64-linux-thread-multi/CORE   -L/usr/local/lib -Wl,--as-needed -o vim        -lm    -ltinfo -lacl -lattr -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26.1/x86_64-linux-thread-multi/CORE  -L/usr/local/lib64 -fstack-protector-strong  -L/usr/lib/perl5/5.26.1/x86_64-linux-thread-multi/CORE -lperl -lm -ldl -lcrypt -lpthread

**Comment by alerque** [comment] 2019-12-03 11:00
I use airline myself and have never seen this. Is anybody able to reproduce it right now? If so lets poke around and see if we can figure out what the cause actually is...

**Comment by alerque** [comment] 2020-05-29 20:19
@FelixZhang Are you able to reproduce this with Universal Ctags? I'm not interested in trying to support Exuberant any more. I won't break it on purpose and I'd be happy to accept contributions that fix for it, but I'm not even going to try to debugging this if it is Exuberant specific. I use Airline myself daily and don't see this problem.

**Comment by raven42** [comment] 2020-10-28 15:11
This should now be fixed with #676 to prevent lookups in the dictionary for unknown kinds. If you are still seeing this issue, please feel free to reopen this issue.

It looks like it is being caused by an unknown kind being reported for a given filetype / language. If you are seeing this issue, then please provide an example source file so we can fix it.

**Closed by raven42** 2020-10-28 15:11 UTC
Labels: unreproducible
