### ISSUE TITLE
Tagbar working for all filetypes but C

### ISSUE THREAD

**Issue by pierz** [preservim/tagbar#488] opened 2018-04-09 13:38 UTC
I've installed and been using tagbar with airline and it works fine with C++/Python and others but it doesn't seem to work with 'C' files - I wondered if there might a way to fix/debug this?  If I do :TagbarToggle it only show one function in the tagbar when there are a number of functions in the c file. I wasn't sure what command to put in my vimrc to enabled debugging of tagbar on startup - I have tried running :TagbarDebug after startup but so far no help? I'm using Universal Ctags who's location is set by g:tagbar_ctags_bin.

**Comment by nicolaiskogheim** [comment] 2018-06-07 11:07
From [`tagbar`s website](http://majutsushi.github.io/tagbar/):

> If you notice that there are some errors in the way your file's structure is displayed in Tagbar, please make sure that the bug is actually in Tagbar before you report an issue. Since Tagbar uses exuberant-ctags and compatible programs to do the actual file parsing, it is likely that the bug is actually in the program responsible for that filetype instead.

> There is an example in :h tagbar-issues about how to run ctags manually so you can determine where the bug actually is. If the bug is actually in ctags, please report it on their website instead, as there is nothing I can do about it in Tagbar. Thank you!

So check out `:h tagbar-issues` for help with finding out whether this is in `tagbar` or `ctags` :)

**Comment by alerque** [comment] 2019-12-03 09:02
I'm unable to replicate this issue as C files work out of the box for me. Did you try running `ctags` on your source files manually yourself and verifying that it's giving output?

**Comment by raven42** [comment] 2020-10-28 15:04
@pierz I am closing out this issue as there hasn't been any update on it or response in a long time, and others are not able to reproduce this issue. If you are still seeing an issue, please use the `:h tagbar-issues` as previously indicated. More info about the source file you're seeing the issue with, and the output of ctags will help diagnose the issue.

**Closed by raven42** 2020-10-28 15:04 UTC
Labels: infoneeded, language-support, unreproducible
